import type { Node } from '@xyflow/react'
import type {
  AgentProvider,
  StandardWindowSizeBucket,
} from '@contexts/settings/domain/agentSettings'
import type { ProjectRoleDefinition } from '@contexts/settings/domain/projectRoles'
import type { WebsiteWindowSessionMode } from '@shared/contracts/dto'
import type {
  DocumentNodeData,
  ImageNodeData,
  NodeFrame,
  Point,
  RoleNodeData,
  Size,
  TerminalNodeData,
  TaskPriority,
  WebsiteNodeData,
} from '../../../types'
import type { WorkspaceSpaceState } from '../../../types'
import type { NodeLabelColorOverride } from '@shared/types/labelColor'
import type {
  CreateNodeInput,
  NodeCreationPlacementOptions,
  NodePlacementOptions,
  ShowWorkspaceCanvasMessage,
} from '../types'

export interface CreateNoteNodeOptions {
  placementStrategy?: 'default' | 'right-no-push'
  placement?: NodePlacementOptions
  initialText?: string
}

export interface UseWorkspaceCanvasNodesStoreParams {
  nodes: Node<TerminalNodeData>[]
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  onShowMessage?: ShowWorkspaceCanvasMessage
  onNodeCreated?: (nodeId: string) => void
  standardWindowSizeBucket: StandardWindowSizeBucket
}

export interface UseWorkspaceCanvasNodeCreationParams {
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onRequestPersistFlush?: () => void
  onShowMessage?: ShowWorkspaceCanvasMessage
  onNodeCreated?: (nodeId: string) => void
  setNodes: UseWorkspaceCanvasNodesStoreResult['setNodes']
  standardWindowSizeBucket: StandardWindowSizeBucket
}

export interface UseWorkspaceCanvasNodesStoreResult {
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  pendingScrollbackByNodeRef: React.MutableRefObject<Map<string, string>>
  isNodeDraggingRef: React.MutableRefObject<boolean>
  setNodes: (
    updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    options?: { syncLayout?: boolean },
  ) => void
  upsertNode: (nextNode: Node<TerminalNodeData>) => void
  bumpAgentLaunchToken: (nodeId: string) => number
  clearAgentLaunchToken: (nodeId: string) => void
  isAgentLaunchTokenCurrent: (nodeId: string, token: number) => boolean
  closeNode: (nodeId: string) => Promise<void>
  normalizePosition: (nodeId: string, desired: Point, size: Size) => Point
  resizeNode: (nodeId: string, desiredFrame: NodeFrame) => void
  applyPendingScrollbacks: (targetNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[]
  updateNodeScrollback: (nodeId: string, scrollback: string) => void
  updateTerminalTitle: (nodeId: string, title: string) => void
  renameTerminalTitle: (nodeId: string, title: string) => void
  setNodeLabelColorOverride: (nodeIds: string[], labelColorOverride: NodeLabelColorOverride) => void
  updateNoteText: (nodeId: string, text: string) => void
  renameNoteTitle: (nodeId: string, title: string) => void
  updateWebsiteUrl: (nodeId: string, url: string) => void
  setWebsitePinned: (nodeId: string, pinned: boolean) => void
  setWebsiteSession: (
    nodeId: string,
    sessionMode: WebsiteWindowSessionMode,
    profileId: string | null,
  ) => void
  createNodeForSession: (input: CreateNodeInput) => Promise<Node<TerminalNodeData> | null>
  createNoteNode: (anchor: Point, options?: CreateNoteNodeOptions) => Node<TerminalNodeData> | null
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
    placement?: NodePlacementOptions,
  ) => Node<TerminalNodeData> | null
  createRoleNode: (
    anchor: Point,
    role: ProjectRoleDefinition,
    placement?: NodePlacementOptions & { selectedProvider?: AgentProvider | null },
  ) => Node<TerminalNodeData> | null
  updateRoleProvider: (nodeId: string, provider: AgentProvider) => void
  updateRoleInput: (nodeId: string, input: string) => void
  appendRoleRunRecord: (
    nodeId: string,
    next: Pick<RoleNodeData, 'linkedAgentNodeId'> & {
      record: RoleNodeData['runHistory'][number]
    },
  ) => void
  createImageNode: (
    anchor: Point,
    image: ImageNodeData,
    placement?: NodeCreationPlacementOptions,
  ) => Node<TerminalNodeData> | null
  createDocumentNode: (
    anchor: Point,
    document: DocumentNodeData,
    placement?: NodeCreationPlacementOptions,
  ) => Node<TerminalNodeData> | null
  createWebsiteNode: (
    anchor: Point,
    website: WebsiteNodeData,
    placement?: NodePlacementOptions,
  ) => Node<TerminalNodeData> | null
}
