import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, readLocatorClientRect } from './workspace-canvas.helpers'
import type { Locator } from '@playwright/test'

async function clickInlineTitleDisplay(display: Locator): Promise<void> {
  await expect(display).toBeVisible()
  await display.evaluate(element => {
    ;(element as HTMLElement).click()
  })
}

async function expectStableRect(
  locator: Locator,
  baseline: { width: number; height: number; x: number; y: number },
): Promise<void> {
  const next = await readLocatorClientRect(locator)

  expect(next.width).toBeCloseTo(baseline.width, 0)
  expect(next.height).toBeCloseTo(baseline.height, 0)
  expect(next.x).toBeCloseTo(baseline.x, 0)
  expect(next.y).toBeCloseTo(baseline.y, 0)
}

test.describe('Workspace Canvas - Header Chrome Stability', () => {
  test('keeps header chrome geometry stable while inline title editing is active', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const longTitle =
        '超长标题超长标题超长标题超长标题超长标题超长标题超长标题超长标题超长标题超长标题'

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'agent-header-stability-task',
            title: 'agent linked task',
            position: { x: 860, y: 120 },
            width: 360,
            height: 280,
            kind: 'task',
            task: {
              requirement: 'Keep header chrome stable while editing the linked agent title.',
              status: 'doing',
              priority: 'medium',
              tags: ['rename'],
              linkedAgentNodeId: 'agent-header-stability',
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'agent-header-stability',
            title: `codex · ${longTitle}`,
            position: { x: 320, y: 120 },
            width: 360,
            height: 300,
            kind: 'agent',
            status: 'running',
            startedAt: '2026-04-29T10:00:00.000Z',
            endedAt: null,
            exitCode: null,
            lastError: null,
            agent: {
              provider: 'codex',
              prompt: 'Measure header chrome while editing the title.',
              model: 'gpt-5.4',
              effectiveModel: 'gpt-5.4',
              launchMode: 'new',
              resumeSessionId: null,
              executionDirectory: '/tmp',
              expectedDirectory: null,
              directoryMode: 'workspace',
              customDirectory: null,
              shouldCreateDirectory: false,
              taskId: 'agent-header-stability-task',
            },
          },
          {
            id: 'task-header-stability',
            title: longTitle,
            position: { x: 860, y: 460 },
            width: 320,
            height: 280,
            kind: 'task',
            task: {
              requirement: 'Keep task header icons stable while editing title.',
              status: 'doing',
              priority: 'medium',
              tags: ['rename'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'note-header-stability',
            title: longTitle,
            position: { x: 320, y: 500 },
            width: 320,
            height: 280,
            kind: 'note',
            task: {
              text: 'Keep note header icons stable while editing title.',
            },
          },
        ],
        {
          settings: { uiTheme: 'light' },
        },
      )

      const sidebarToggle = window.locator('[data-testid="workspace-sidebar-pin"]')
      await expect(sidebarToggle).toBeVisible()
      await sidebarToggle.click()
      await expect(window.locator('.app-shell--sidebar-collapsed')).toHaveCount(1)
      await window.waitForTimeout(200)

      const agentNode = window
        .locator('.terminal-node')
        .filter({ has: window.locator('.terminal-node__status') })
        .first()
      const taskNode = window.locator('.task-node').last()
      const noteNode = window.locator('.note-node').first()

      const agentTitleDisplay = agentNode.locator('[data-testid="terminal-node-title-display"]')
      const agentTitleInput = agentNode.locator('[data-testid="terminal-node-inline-title-input"]')
      const agentStatus = agentNode.locator('.terminal-node__status')
      const agentClose = agentNode.locator('.terminal-node__close')

      const taskTitleDisplay = taskNode.locator('[data-testid="task-node-title-display"]')
      const taskTitleInput = taskNode.locator('[data-testid="task-node-inline-title-input"]')
      const taskEditButton = taskNode.locator('.task-node__icon-button--edit')
      const taskCloseButton = taskNode.locator('.task-node__icon-button--close')

      const noteTitleDisplay = noteNode.locator('[data-testid="note-node-title-display"]')
      const noteTitleInput = noteNode.locator('[data-testid="note-node-title-input"]')
      const noteActionButton = noteNode.locator('.note-node__action')
      const noteCloseButton = noteNode.locator('.note-node__close')

      const agentStatusRect = await readLocatorClientRect(agentStatus)
      const agentCloseRect = await readLocatorClientRect(agentClose)
      const taskEditRect = await readLocatorClientRect(taskEditButton)
      const taskCloseRect = await readLocatorClientRect(taskCloseButton)
      const noteActionRect = await readLocatorClientRect(noteActionButton)
      const noteCloseRect = await readLocatorClientRect(noteCloseButton)

      await clickInlineTitleDisplay(agentTitleDisplay)
      await expect(agentTitleInput).toBeVisible({ timeout: 30_000 })
      await expectStableRect(agentStatus, agentStatusRect)
      await expectStableRect(agentClose, agentCloseRect)
      await agentTitleInput.press('Escape')
      await expect(agentTitleInput).toHaveCount(0)

      await clickInlineTitleDisplay(taskTitleDisplay)
      await expect(taskTitleInput).toBeVisible({ timeout: 30_000 })
      await expectStableRect(taskEditButton, taskEditRect)
      await expectStableRect(taskCloseButton, taskCloseRect)
      await taskTitleInput.press('Escape')
      await expect(taskTitleInput).toHaveCount(0)

      await clickInlineTitleDisplay(noteTitleDisplay)
      await expect(noteTitleInput).toBeVisible({ timeout: 30_000 })
      await expectStableRect(noteActionButton, noteActionRect)
      await expectStableRect(noteCloseButton, noteCloseRect)
      await noteTitleInput.press('Escape')
      await expect(noteTitleInput).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })
})
