import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, readLocatorClientRect } from './workspace-canvas.helpers'
import type { Locator } from '@playwright/test'

async function readInlineTitleDisplayMetrics(display: Locator): Promise<{
  text: string
  clientWidth: number
  scrollWidth: number
}> {
  await expect(display).toBeVisible()

  return await display.evaluate(element => {
    const textElement = element.querySelector('.node-title-editor__display-text')
    return {
      text: element.textContent?.trim() ?? '',
      clientWidth: textElement instanceof HTMLElement ? textElement.clientWidth : 0,
      scrollWidth: textElement instanceof HTMLElement ? textElement.scrollWidth : 0,
    }
  })
}

async function readInlineTitleInputMetrics(input: Locator): Promise<{
  value: string
  clientWidth: number
  scrollWidth: number
  scrollLeft: number
  selectionStart: number
  selectionEnd: number
}> {
  await expect(input).toBeVisible()

  return await input.evaluate(element => ({
    value: element.value,
    clientWidth: element.clientWidth,
    scrollWidth: element.scrollWidth,
    scrollLeft: element.scrollLeft,
    selectionStart: element.selectionStart ?? -1,
    selectionEnd: element.selectionEnd ?? -1,
  }))
}

test.describe('Workspace Canvas - Inline Title Editor', () => {
  test('keeps long note title drafts aligned while editing', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'note-inline-title-editing',
            title: 'note',
            position: { x: 260, y: 180 },
            width: 420,
            height: 280,
            kind: 'note',
            task: {
              text: 'Inline title editing should remain readable.',
            },
          },
        ],
        {
          settings: { uiTheme: 'light' },
        },
      )

      const longTitle =
        '超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题'

      const sidebarToggle = window.locator('[data-testid="workspace-sidebar-pin"]')
      await expect(sidebarToggle).toBeVisible()
      await sidebarToggle.click()
      await expect(window.locator('.app-shell--sidebar-collapsed')).toHaveCount(1)

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      const noteNode = window.locator('.note-node').first()
      const titleDisplay = noteNode.locator('[data-testid="note-node-title-display"]')
      const titleInput = noteNode.locator('[data-testid="note-node-title-input"]')

      await expect(pane).toBeVisible()
      await titleDisplay.click()
      await expect(titleInput).toBeVisible({ timeout: 30_000 })
      await titleInput.fill('')
      await titleInput.type(longTitle, { delay: 8 })
      await window.waitForTimeout(80)

      const editingMetrics = await readInlineTitleInputMetrics(titleInput)
      expect(editingMetrics.value).toBe(longTitle)
      expect(editingMetrics.clientWidth).toBeGreaterThan(180)
      expect(editingMetrics.scrollWidth).toBeGreaterThan(editingMetrics.clientWidth)
      expect(editingMetrics.selectionStart).toBe(longTitle.length)
      expect(editingMetrics.selectionEnd).toBe(longTitle.length)
      expect(editingMetrics.scrollLeft).toBeGreaterThan(0)

      await pane.click({ position: { x: 1080, y: 620 } })
      await expect(titleInput).toHaveCount(0)

      const displayMetrics = await readInlineTitleDisplayMetrics(titleDisplay)
      expect(displayMetrics.text).toBe(longTitle)
      expect(displayMetrics.clientWidth).toBeGreaterThan(180)
      expect(displayMetrics.scrollWidth).toBeGreaterThan(displayMetrics.clientWidth)
    } finally {
      await electronApp.close()
    }
  })

  test('gives note and task titles similar usable width to terminal titles', async () => {
    const { electronApp, window } = await launchApp()

    try {
      const longTitle =
        '超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题超长便签标题'

      await clearAndSeedWorkspace(
        window,
        [
          {
            id: 'terminal-inline-title-width',
            title: longTitle,
            position: { x: 220, y: 140 },
            width: 520,
            height: 300,
            kind: 'terminal',
          },
          {
            id: 'task-inline-title-width',
            title: longTitle,
            position: { x: 780, y: 140 },
            width: 520,
            height: 280,
            kind: 'task',
            task: {
              requirement: 'Task title width should stay close to terminal title width.',
              status: 'doing',
              priority: 'medium',
              tags: ['rename'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
            },
          },
          {
            id: 'note-inline-title-width',
            title: longTitle,
            position: { x: 220, y: 500 },
            width: 520,
            height: 280,
            kind: 'note',
            task: {
              text: 'Note title width should stay close to terminal title width.',
            },
          },
        ],
        {
          settings: { uiTheme: 'light' },
        },
      )

      const sidebarToggle = window.locator('[data-testid="workspace-sidebar-pin"]')
      await expect(sidebarToggle).toBeVisible()
      await sidebarToggle.click()
      await expect(window.locator('.app-shell--sidebar-collapsed')).toHaveCount(1)

      const terminalHeader = window.locator('.terminal-node__header').first()
      const taskHeader = window.locator('.task-node__header').first()
      const noteHeader = window.locator('.note-node__header').first()
      const terminalDisplay = window.locator('[data-testid="terminal-node-title-display"]').first()
      const taskDisplay = window.locator('[data-testid="task-node-title-display"]').first()
      const noteDisplay = window.locator('[data-testid="note-node-title-display"]').first()

      const [terminalHeaderRect, taskHeaderRect, noteHeaderRect] = await Promise.all([
        readLocatorClientRect(terminalHeader),
        readLocatorClientRect(taskHeader),
        readLocatorClientRect(noteHeader),
      ])
      const [terminalMetrics, taskMetrics, noteMetrics] = await Promise.all([
        readInlineTitleDisplayMetrics(terminalDisplay),
        readInlineTitleDisplayMetrics(taskDisplay),
        readInlineTitleDisplayMetrics(noteDisplay),
      ])

      expect(terminalMetrics.clientWidth).toBeGreaterThan(terminalHeaderRect.width * 0.5)
      expect(taskMetrics.clientWidth).toBeGreaterThan(taskHeaderRect.width * 0.5)
      expect(noteMetrics.clientWidth).toBeGreaterThan(noteHeaderRect.width * 0.5)
      expect(Math.abs(taskMetrics.clientWidth - terminalMetrics.clientWidth)).toBeLessThan(96)
      expect(Math.abs(noteMetrics.clientWidth - terminalMetrics.clientWidth)).toBeLessThan(96)
    } finally {
      await electronApp.close()
    }
  })
})
