import { expect, test, type Locator, type Page } from '@playwright/test'
import { writeFile } from 'node:fs/promises'
import {
  clearAndSeedWorkspace,
  launchApp,
  readCanvasViewport,
  seedWorkspaceState,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function readAgentLandingGeometry(
  window: Page,
  agentNode: Locator,
): Promise<{ deltaX: number; deltaY: number }> {
  return await agentNode.evaluate(element => {
    const agentRect = element.getBoundingClientRect()
    const header = document.querySelector('.app-header')
    const sidebar = document.querySelector('.workspace-sidebar')
    const headerRect = header instanceof HTMLElement ? header.getBoundingClientRect() : null
    const sidebarRect = sidebar instanceof HTMLElement ? sidebar.getBoundingClientRect() : null
    const contentLeft = sidebarRect ? sidebarRect.right : 0
    const contentTop = headerRect ? headerRect.bottom : 0
    const expectedCenterX = contentLeft + (window.innerWidth - contentLeft) / 2
    const expectedCenterY = contentTop + (window.innerHeight - contentTop) / 2

    return {
      deltaX: agentRect.left + agentRect.width / 2 - expectedCenterX,
      deltaY: agentRect.top + agentRect.height / 2 - expectedCenterY,
    }
  })
}

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-status-watch',
        title: 'Trace flaky status updates',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Reproduce watcher status transitions and verify standby refresh',
          status: 'todo',
          priority: 'medium',
          tags: ['debug'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-07T12:00:00.000Z',
          updatedAt: '2026-03-07T12:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: 'gpt-5.2-codex',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: ['gpt-5.2-codex'],
        },
      },
    },
  )
}

async function seedCodexTaskInMultipleWorkspaces(
  window: Awaited<ReturnType<typeof launchApp>>['window'],
) {
  await seedWorkspaceState(window, {
    activeWorkspaceId: 'workspace-a',
    workspaces: [
      {
        id: 'workspace-a',
        name: 'workspace-a',
        path: testWorkspacePath,
        nodes: [
          {
            id: 'task-status-watch',
            title: 'Trace flaky status updates',
            position: { x: 180, y: 140 },
            width: 460,
            height: 280,
            kind: 'task',
            status: null,
            task: {
              requirement: 'Reproduce watcher status transitions and verify standby refresh',
              status: 'todo',
              priority: 'medium',
              tags: ['debug'],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: '2026-03-07T12:00:00.000Z',
              updatedAt: '2026-03-07T12:00:00.000Z',
            },
          },
        ],
      },
      {
        id: 'workspace-b',
        name: 'workspace-b',
        path: `${testWorkspacePath}-b`,
        nodes: [],
      },
    ],
    settings: {
      defaultProvider: 'codex',
      customModelEnabledByProvider: {
        'claude-code': false,
        codex: true,
      },
      customModelByProvider: {
        'claude-code': '',
        codex: 'gpt-5.2-codex',
      },
      customModelOptionsByProvider: {
        'claude-code': [],
        codex: ['gpt-5.2-codex'],
      },
      focusNodeTargetZoom: 1,
      focusNodeUseVisibleCanvasCenter: true,
    },
  })
}

test.describe('Workspace Canvas - Agent Status Watcher', () => {
  test('updates an active agent from working to standby when the last session line has no newline', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTask(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()
      const taskStatus = taskNode.locator('[data-testid="task-node-status-select"]')

      await expect(agentNode).toBeVisible()
      await expect(taskStatus).toHaveValue('doing')
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')

      const notification = window
        .locator('[data-testid="app-notifications"] .app-notification')
        .first()
      await expect(notification).toBeVisible()

      await window.waitForTimeout(800)
      await expect(notification).toBeVisible()

      await window.locator('[data-testid^="app-notification-close-"]').first().click()
      await expect(window.locator('[data-testid="app-notifications"]')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })

  test('opens a non-focused project notification at the corresponding agent', async ({
    browserName: _browserName,
  }, testInfo) => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-no-newline',
      },
    })

    try {
      await seedCodexTaskInMultipleWorkspaces(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      await expect(agentNode).toBeVisible()

      const workspaceAGroup = window
        .locator('.workspace-item-group')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-a' }) })

      const workspaceAStatus = workspaceAGroup
        .locator('.workspace-agent-item__status--agent')
        .first()

      await expect(workspaceAStatus).toHaveText('Working')

      await window.locator('.workspace-item__name', { hasText: 'workspace-b' }).click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-b',
      )

      await expect(workspaceAStatus).toHaveText('Standby', { timeout: 15_000 })

      const notification = window
        .locator('[data-testid="app-notifications"] .app-notification')
        .first()
      await expect(notification).toBeVisible()

      await window.locator('.workspace-item__name', { hasText: 'workspace-a' }).click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-a',
      )
      await window.locator('.react-flow__controls-fitview').click()
      const viewportBeforeSwitch = await readCanvasViewport(window)
      const landingBeforeSwitch = await readAgentLandingGeometry(window, agentNode)
      expect(Math.hypot(landingBeforeSwitch.deltaX, landingBeforeSwitch.deltaY)).toBeGreaterThan(80)
      await window.screenshot({ path: testInfo.outputPath('notification-agent-before.png') })

      await window.locator('.workspace-item__name', { hasText: 'workspace-b' }).click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-b',
      )
      await notification.click()

      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-a',
      )
      await expect(window.locator('[data-testid="app-notifications"]')).toHaveCount(0)
      await expect
        .poll(async () => {
          const landing = await readAgentLandingGeometry(window, agentNode)
          return Math.hypot(landing.deltaX, landing.deltaY)
        })
        .toBeLessThan(3)
      await expect
        .poll(async () => {
          return (await readCanvasViewport(window)).zoom
        })
        .toBeCloseTo(1, 2)

      const viewportAfterNotification = await readCanvasViewport(window)
      const landingAfterNotification = await readAgentLandingGeometry(window, agentNode)
      expect(
        Math.hypot(
          viewportAfterNotification.x - viewportBeforeSwitch.x,
          viewportAfterNotification.y - viewportBeforeSwitch.y,
        ),
      ).toBeGreaterThan(30)
      await window.screenshot({ path: testInfo.outputPath('notification-agent-after.png') })
      const measurementPath = testInfo.outputPath('notification-agent-landing.json')
      await writeFile(
        measurementPath,
        JSON.stringify(
          {
            before: { viewport: viewportBeforeSwitch, landing: landingBeforeSwitch },
            after: {
              viewport: viewportAfterNotification,
              landing: landingAfterNotification,
            },
          },
          null,
          2,
        ),
      )
      await testInfo.attach('notification-agent-landing-measurement', {
        path: measurementPath,
        contentType: 'application/json',
      })
    } finally {
      await electronApp.close()
    }
  })

  test('shows a notification even if the first observed state is standby after switching projects', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-standby-only',
      },
    })

    try {
      await seedCodexTaskInMultipleWorkspaces(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const workspaceAGroup = window
        .locator('.workspace-item-group')
        .filter({ has: window.locator('.workspace-item__name', { hasText: 'workspace-a' }) })

      const workspaceAStatus = workspaceAGroup
        .locator('.workspace-agent-item__status--agent')
        .first()

      await expect(workspaceAStatus).toHaveText('Working')

      await window.locator('.workspace-item__name', { hasText: 'workspace-b' }).click()
      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-b',
      )

      await expect(workspaceAStatus).toHaveText('Standby', { timeout: 15_000 })

      const notification = window
        .locator('[data-testid="app-notifications"] .app-notification')
        .first()
      await expect(notification).toBeVisible()
      await notification.click()

      await expect(window.locator('.workspace-item.workspace-item--active')).toContainText(
        'workspace-a',
      )
      await expect(window.locator('[data-testid="app-notifications"]')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })

  test('keeps codex in working during commentary until the final answer arrives', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-commentary-then-final',
      },
    })

    try {
      await seedCodexTask(window)

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const sidebarStatus = window
        .locator('.workspace-sidebar .workspace-agent-item .workspace-agent-item__status--agent')
        .first()

      await expect(agentNode).toBeVisible()
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await window.waitForTimeout(2600)
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await window.waitForTimeout(1400)
      await expect(nodeStatus).toHaveText('Working')
      await expect(sidebarStatus).toHaveText('Working')

      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })
      await expect(sidebarStatus).toHaveText('Standby')
    } finally {
      await electronApp.close()
    }
  })
})
