import type { Node } from '@xyflow/react'
import type {
  DocumentNodeData,
  ImageNodeData,
  NoteNodeData,
  PersistedWorkspaceState,
  RoleNodeData,
  TaskNodeData,
  TerminalNodeData,
  WebsiteNodeData,
} from '../types'

function isTaskNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is TaskNodeData {
  return value !== null && typeof value === 'object' && 'requirement' in value
}

function isNoteNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is NoteNodeData {
  return value !== null && typeof value === 'object' && 'text' in value
}

function isImageNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is ImageNodeData {
  return value !== null && typeof value === 'object' && 'assetId' in value && 'mimeType' in value
}

function isDocumentNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is DocumentNodeData {
  return value !== null && typeof value === 'object' && 'uri' in value
}

function isWebsiteNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is WebsiteNodeData {
  return value !== null && typeof value === 'object' && 'url' in value && 'sessionMode' in value
}

function isRoleNodeData(
  value:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null,
): value is RoleNodeData {
  return (
    value !== null && typeof value === 'object' && 'roleId' in value && 'promptTemplate' in value
  )
}

export function toRuntimeNodes(workspace: PersistedWorkspaceState): Node<TerminalNodeData>[] {
  return workspace.nodes.map(node => {
    const defaultTask: TaskNodeData = {
      requirement: '',
      status: 'todo',
      priority: 'medium',
      tags: [],
      linkedAgentNodeId: null,
      agentSessions: [],
      lastRunAt: null,
      autoGeneratedTitle: false,
      createdAt: null,
      updatedAt: null,
    }
    const task: TaskNodeData | null =
      node.kind === 'task' ? (isTaskNodeData(node.task) ? node.task : defaultTask) : null
    const note =
      node.kind === 'note' ? (isNoteNodeData(node.task) ? node.task : { text: '' }) : null
    const role: RoleNodeData | null =
      node.kind === 'role'
        ? isRoleNodeData(node.task)
          ? node.task
          : {
              roleId: '',
              roleName: node.title,
              roleDescription: '',
              promptTemplate: '',
              inputHint: '',
              outputFormat: '',
              input: '',
              selectedProvider: null,
              linkedAgentNodeId: null,
              runHistory: [],
              createdAt: null,
              updatedAt: null,
            }
        : null
    const image: ImageNodeData | null =
      node.kind === 'image' ? (isImageNodeData(node.task) ? node.task : null) : null
    const document: DocumentNodeData | null =
      node.kind === 'document' ? (isDocumentNodeData(node.task) ? node.task : null) : null
    const website: WebsiteNodeData | null =
      node.kind === 'website' ? (isWebsiteNodeData(node.task) ? node.task : null) : null

    const runtimeNode: Node<TerminalNodeData> = {
      id: node.id,
      type:
        node.kind === 'task'
          ? 'taskNode'
          : node.kind === 'note'
            ? 'noteNode'
            : node.kind === 'image'
              ? 'imageNode'
              : node.kind === 'role'
                ? 'roleNode'
                : node.kind === 'document'
                  ? 'documentNode'
                  : node.kind === 'website'
                    ? 'websiteNode'
                    : 'terminalNode',
      position: node.position,
      initialWidth: node.width,
      initialHeight: node.height,
      data: {
        sessionId: typeof node.sessionId === 'string' ? node.sessionId : '',
        isLiveSessionReattach: false,
        profileId: node.profileId,
        runtimeKind: node.runtimeKind,
        terminalGeometry: node.terminalGeometry ?? null,
        terminalProviderHint: node.terminalProviderHint ?? null,
        labelColorOverride: node.labelColorOverride ?? null,
        title: node.title,
        titlePinnedByUser: node.titlePinnedByUser === true,
        width: node.width,
        height: node.height,
        kind: node.kind,
        status: node.status,
        startedAt: node.startedAt,
        endedAt: node.endedAt,
        exitCode: node.exitCode,
        lastError: node.lastError,
        scrollback: node.scrollback,
        executionDirectory: node.executionDirectory,
        expectedDirectory: node.expectedDirectory,
        agent: node.agent,
        task,
        note,
        role,
        image,
        document,
        website,
      },
      draggable: true,
      selectable: node.kind !== 'note' && node.kind !== 'document',
    }

    return runtimeNode
  })
}
