import { beforeEach, describe, expect, it } from 'vitest'
import {
  readPersistedState,
  toPersistedState,
  writePersistedState,
  writeRawPersistedState,
} from '../../../src/contexts/workspace/presentation/renderer/utils/persistence'
import { DEFAULT_WORKSPACE_VIEWPORT } from '../../../src/contexts/workspace/presentation/renderer/types'
import type { WorkspaceState } from '../../../src/contexts/workspace/presentation/renderer/types'
import { installMockStorage } from '../../support/persistenceTestStorage'

installMockStorage()

beforeEach(() => {
  window.localStorage.clear()
})

describe('workspace persistence (read/normalize)', () => {
  it('writes and reads persisted state', async () => {
    const workspaces: WorkspaceState[] = [
      {
        id: 'workspace-1',
        name: 'cove',
        path: '/tmp/cove',
        worktreesRoot: '.opencove/worktrees',
        spaceArchiveRecords: [],
        viewport: { x: -320, y: 180, zoom: 1.25 },
        isMinimapVisible: false,
        spaces: [],
        activeSpaceId: null,
        nodes: [
          {
            id: 'node-1',
            type: 'terminalNode',
            position: { x: 100, y: 80 },
            data: {
              sessionId: 'session-1',
              title: 'terminal-1',
              width: 460,
              height: 300,
              kind: 'terminal',
              status: null,
              startedAt: null,
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: 'terminal output line 1\nterminal output line 2\n',
              agent: null,
              task: null,
            },
          },
          {
            id: 'node-task',
            type: 'taskNode',
            position: { x: 240, y: 220 },
            data: {
              sessionId: '',
              title: 'Retry Login Requests',
              width: 460,
              height: 280,
              kind: 'task',
              status: null,
              startedAt: null,
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: null,
              agent: null,
              task: {
                requirement: 'Implement retry with backoff and jitter',
                status: 'doing',
                linkedAgentNodeId: 'node-agent',
                lastRunAt: '2026-02-08T16:12:00.000Z',
                autoGeneratedTitle: true,
              },
            },
          },
          {
            id: 'node-agent',
            type: 'terminalNode',
            position: { x: 640, y: 120 },
            data: {
              sessionId: 'session-agent-1',
              title: 'codex · gpt-5.2-codex',
              width: 500,
              height: 320,
              kind: 'agent',
              status: 'running',
              startedAt: '2026-02-08T16:10:00.000Z',
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: '[opencove-test-agent] codex new gpt-5.2-codex\n',
              agent: {
                provider: 'codex',
                prompt: 'Implement retry for failed request',
                model: 'gpt-5.2-codex',
                effectiveModel: 'gpt-5.2-codex',
                launchMode: 'new',
                resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
                executionDirectory: '/tmp/cove',
                directoryMode: 'workspace',
                customDirectory: null,
                shouldCreateDirectory: false,
                taskId: 'node-task',
              },
              task: null,
            },
          },
        ],
      },
    ]

    const persisted = toPersistedState(workspaces, 'workspace-1', {
      defaultProvider: 'claude-code',
      customModelEnabledByProvider: {
        'claude-code': false,
        codex: true,
      },
      customModelByProvider: {
        'claude-code': '',
        codex: 'gpt-5.2-codex',
      },
      customModelOptionsByProvider: {
        'claude-code': ['claude-opus-4-6'],
        codex: ['gpt-5.2-codex'],
      },
      taskTitleProvider: 'codex',
      taskTitleModel: 'gpt-5.2-codex',
      taskTagOptions: ['feature', 'bug'],
      focusNodeOnClick: false,
      focusNodeTargetZoom: 1.25,
      canvasInputMode: 'trackpad',
    })

    await writePersistedState(persisted)

    const restored = await readPersistedState()

    expect(restored).not.toBeNull()
    expect(restored?.activeWorkspaceId).toBe('workspace-1')
    expect(restored?.workspaces).toHaveLength(1)
    expect(restored?.workspaces[0].viewport).toEqual({ x: -320, y: 180, zoom: 1.25 })
    expect(restored?.workspaces[0].isMinimapVisible).toBe(false)
    expect(restored?.workspaces[0].worktreesRoot).toBe('.opencove/worktrees')
    expect(restored?.workspaces[0].nodes).toHaveLength(3)
    expect(restored?.workspaces[0].nodes[0].title).toBe('terminal-1')
    expect(restored?.workspaces[0].nodes[0].scrollback).toBeNull()
    expect(restored?.workspaces[0].nodes[1].kind).toBe('task')
    expect(restored?.workspaces[0].nodes[1].task?.status).toBe('doing')
    expect(restored?.workspaces[0].nodes[2].kind).toBe('agent')
    expect(restored?.workspaces[0].nodes[2].agent?.provider).toBe('codex')
    expect(restored?.workspaces[0].nodes[2].agent?.resumeSessionIdVerified).toBe(false)
    expect(restored?.workspaces[0].spaces).toEqual([])
    expect(restored?.workspaces[0].activeSpaceId).toBeNull()
    expect(restored?.settings.defaultProvider).toBe('claude-code')
    expect(restored?.settings.customModelEnabledByProvider.codex).toBe(true)
    expect(restored?.settings.customModelByProvider.codex).toBe('gpt-5.2-codex')
    expect(restored?.settings.customModelOptionsByProvider['claude-code']).toEqual([
      'claude-opus-4-6',
    ])
    expect(restored?.settings.customModelOptionsByProvider.codex).toEqual(['gpt-5.2-codex'])
    expect(restored?.settings.taskTitleProvider).toBe('codex')
    expect(restored?.settings.taskTitleModel).toBe('gpt-5.2-codex')
    expect(restored?.settings.taskTagOptions).toEqual(['feature', 'bug'])
    expect(restored?.settings.focusNodeOnClick).toBe(false)
    expect(restored?.settings.focusNodeTargetZoom).toBe(1.25)
    expect(restored?.settings.canvasInputMode).toBe('trackpad')
  })

  it('does not persist terminal scrollback in app state payload', async () => {
    const prefix = 'old\n'
    const suffix = 'tail\n'
    const oversized = `${prefix}${'x'.repeat(260_000)}${suffix}`

    const persisted = toPersistedState(
      [
        {
          id: 'workspace-1',
          name: 'cove',
          path: '/tmp/cove',
          worktreesRoot: '',
          viewport: { x: 0, y: 0, zoom: 1 },
          isMinimapVisible: true,
          spaces: [],
          activeSpaceId: null,
          spaceArchiveRecords: [],
          nodes: [
            {
              id: 'terminal-1',
              type: 'terminalNode',
              position: { x: 120, y: 120 },
              data: {
                sessionId: 'session-1',
                title: 'terminal-1',
                width: 460,
                height: 300,
                kind: 'terminal',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: oversized,
                agent: null,
                task: null,
              },
            },
          ],
        },
      ],
      'workspace-1',
    )

    await writePersistedState(persisted)

    const restored = await readPersistedState()
    expect(restored?.workspaces[0]?.nodes[0]?.scrollback).toBeNull()
  })

  it('falls back to default settings when persisted settings are missing', async () => {
    await writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: null,
        workspaces: [],
      }),
    )

    const restored = await readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.settings.defaultProvider).toBe('codex')
    expect(restored?.settings.customModelEnabledByProvider['claude-code']).toBe(false)
    expect(restored?.settings.customModelByProvider['claude-code']).toBe('')
    expect(restored?.settings.customModelOptionsByProvider['claude-code']).toEqual([])
    expect(restored?.settings.customModelOptionsByProvider.codex).toEqual([])
    expect(restored?.settings.taskTitleProvider).toBe('default')
    expect(restored?.settings.taskTitleModel).toBe('')
    expect(restored?.settings.taskTagOptions).toEqual([
      'feature',
      'bug',
      'refactor',
      'docs',
      'test',
    ])
    expect(restored?.settings.focusNodeOnClick).toBe(true)
    expect(restored?.settings.focusNodeTargetZoom).toBe(1)
    expect(restored?.settings.canvasInputMode).toBe('auto')
  })

  it('fills missing workspace viewport fields for legacy payload', async () => {
    await writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            nodes: [],
          },
        ],
        settings: {},
      }),
    )

    const restored = await readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.workspaces).toHaveLength(1)
    expect(restored?.workspaces[0].viewport).toEqual(DEFAULT_WORKSPACE_VIEWPORT)
    expect(restored?.workspaces[0].isMinimapVisible).toBe(true)
    expect(restored?.workspaces[0].spaces).toEqual([])
    expect(restored?.workspaces[0].activeSpaceId).toBeNull()
  })

  it('persists workspace spaces and active space id', async () => {
    await writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            viewport: { x: 0, y: 0, zoom: 1 },
            isMinimapVisible: true,
            nodes: [
              {
                id: 'node-1',
                title: 'terminal-1',
                position: { x: 120, y: 140 },
                width: 460,
                height: 300,
                kind: 'terminal',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: null,
                agent: null,
                task: null,
              },
            ],
            spaces: [
              {
                id: 'space-1',
                name: 'Backlog',
                directoryPath: '/tmp/cove',
                nodeIds: ['node-1'],
                rect: {
                  x: 10,
                  y: 20,
                  width: 300,
                  height: 240,
                },
              },
            ],
            activeSpaceId: 'space-1',
          },
        ],
        settings: {},
      }),
    )

    const restored = await readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.workspaces[0].spaces).toHaveLength(1)
    expect(restored?.workspaces[0].spaces[0].name).toBe('Backlog')
    expect(restored?.workspaces[0].spaces[0].directoryPath).toBe('/tmp/cove')
    expect(restored?.workspaces[0].spaces[0].nodeIds).toEqual(['node-1'])
    expect(restored?.workspaces[0].activeSpaceId).toBe('space-1')
  })

  it('normalizes persisted role nodes and project role settings', async () => {
    await writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            nodes: [
              {
                id: 'node-role',
                title: 'Product Manager',
                position: { x: 120, y: 140 },
                width: 360,
                height: 320,
                kind: 'role',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: null,
                agent: null,
                task: {
                  roleId: 'role-pm',
                  roleName: 'Product Manager',
                  roleDescription: 'Own requirements',
                  promptTemplate: 'Write product requirements.',
                  inputHint: 'Feature brief',
                  outputFormat: 'PRD',
                  input: 'Build role chaining.',
                  selectedProvider: 'claude-code',
                  linkedAgentNodeId: 'node-agent',
                  runHistory: [
                    {
                      id: 'run-1',
                      input: 'Build role chaining.',
                      prompt: 'Write product requirements.',
                      outputFormat: 'PRD',
                      provider: 'claude-code',
                      agentNodeId: 'node-agent',
                      sessionId: 'session-agent',
                      createdAt: '2026-05-10T00:00:00.000Z',
                    },
                  ],
                  createdAt: '2026-05-10T00:00:00.000Z',
                  updatedAt: '2026-05-10T00:00:00.000Z',
                },
              },
            ],
          },
        ],
        settings: {
          projectRolesByWorkspaceId: {
            'workspace-1': [
              {
                id: 'role-pm',
                name: 'Product Manager',
                promptTemplate: 'Write product requirements.',
              },
            ],
          },
        },
      }),
    )

    const restored = await readPersistedState()
    const roleNode = restored?.workspaces[0]?.nodes[0]

    expect(roleNode?.kind).toBe('role')
    expect(roleNode?.task).toMatchObject({
      roleId: 'role-pm',
      roleName: 'Product Manager',
      input: 'Build role chaining.',
      selectedProvider: 'claude-code',
      linkedAgentNodeId: 'node-agent',
    })
    expect(restored?.settings.projectRolesByWorkspaceId['workspace-1']?.[0]).toMatchObject({
      id: 'role-pm',
      name: 'Product Manager',
      promptTemplate: 'Write product requirements.',
    })
  })

  it('clamps space archive records to 50 items when reading', async () => {
    const spaceArchiveRecords = Array.from({ length: 55 }, (_, index) => ({
      id: `archive-${index}`,
      archivedAt: '2026-03-23T00:00:00.000Z',
      space: {
        id: 'space-1',
        name: 'Archived Space',
        directoryPath: '/tmp/cove',
        labelColor: null,
        rect: null,
      },
      nodes: [],
    }))

    await writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            nodes: [],
            spaceArchiveRecords,
          },
        ],
        settings: {},
      }),
    )

    const restored = await readPersistedState()
    expect(restored?.workspaces[0].spaceArchiveRecords).toHaveLength(50)
    expect(restored?.workspaces[0].spaceArchiveRecords[0]?.id).toBe('archive-0')
    expect(restored?.workspaces[0].spaceArchiveRecords.some(item => item.id === 'archive-54')).toBe(
      false,
    )
  })

  it('returns null when stored json is invalid', async () => {
    await writeRawPersistedState('{')
    expect(await readPersistedState()).toBeNull()
  })
})
