import type { Node } from '@xyflow/react'
import { describe, expect, it } from 'vitest'
import type {
  SpaceArchiveRecord,
  TerminalNodeData,
  WorkspaceSpaceState,
} from '../../../src/contexts/workspace/presentation/renderer/types'
import {
  appendSpaceArchiveRecord,
  buildSpaceArchiveRecord,
  getSpaceArchiveRecordSpaces,
} from '../../../src/contexts/workspace/presentation/renderer/utils/spaceArchiveRecords'

function createNoteNode(id: string, text: string): Node<TerminalNodeData> {
  return {
    id,
    position: { x: 0, y: 0 },
    data: {
      sessionId: '',
      title: id,
      width: 320,
      height: 220,
      kind: 'note',
      status: null,
      startedAt: null,
      endedAt: null,
      exitCode: null,
      lastError: null,
      scrollback: null,
      executionDirectory: null,
      expectedDirectory: null,
      agent: null,
      task: null,
      note: { text },
    },
  }
}

describe('space archive records', () => {
  it('captures full text without terminal scrollback', () => {
    const nodes: Array<Node<TerminalNodeData>> = [
      {
        id: 'note-1',
        position: { x: 0, y: 0 },
        data: {
          sessionId: '',
          title: 'Note Title',
          width: 320,
          height: 220,
          kind: 'note',
          status: null,
          startedAt: null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          executionDirectory: null,
          expectedDirectory: null,
          agent: null,
          task: null,
          note: {
            text: 'Note full text\nLine 2',
          },
        },
      },
      {
        id: 'task-1',
        position: { x: 100, y: 80 },
        data: {
          sessionId: '',
          title: 'Task Title',
          width: 420,
          height: 260,
          kind: 'task',
          status: null,
          startedAt: null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          executionDirectory: null,
          expectedDirectory: null,
          agent: null,
          task: {
            requirement: 'Task requirement full text\nLine 2',
            status: 'doing',
            priority: 'high',
            tags: ['bugfix'],
            linkedAgentNodeId: null,
            agentSessions: [],
            lastRunAt: null,
            autoGeneratedTitle: false,
            createdAt: null,
            updatedAt: null,
          },
          note: null,
        },
      },
      {
        id: 'terminal-1',
        position: { x: 220, y: 40 },
        data: {
          sessionId: 'session-1',
          title: 'Terminal Title',
          width: 520,
          height: 320,
          kind: 'terminal',
          status: null,
          startedAt: null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: 'should not be captured',
          executionDirectory: '/tmp/cove',
          expectedDirectory: '/tmp/cove',
          agent: null,
          task: null,
          note: null,
        },
      },
    ]

    const space: WorkspaceSpaceState = {
      id: 'space-1',
      name: 'Archived Space',
      directoryPath: '/tmp/cove',
      targetMountId: null,
      labelColor: null,
      nodeIds: ['note-1', 'task-1', 'terminal-1'],
      rect: null,
    }

    const record = buildSpaceArchiveRecord({
      space,
      nodes,
      archivedAt: '2026-03-23T00:00:00.000Z',
      recordId: 'record-1',
    })

    expect(record.id).toBe('record-1')
    expect(record.space.name).toBe('Archived Space')
    expect(record.git).toBeNull()
    expect(record.nodes).toHaveLength(3)

    const noteSnapshot = record.nodes.find(node => node.kind === 'note')
    expect(noteSnapshot && noteSnapshot.kind === 'note' ? noteSnapshot.text : null).toBe(
      'Note full text\nLine 2',
    )
    expect(noteSnapshot?.labelColorOverride).toBeNull()
    expect(noteSnapshot?.frame?.position).toEqual({ x: 0, y: 0 })
    expect(noteSnapshot?.frame?.size).toEqual({ width: 320, height: 220 })

    const taskSnapshot = record.nodes.find(node => node.kind === 'task')
    expect(taskSnapshot && taskSnapshot.kind === 'task' ? taskSnapshot.requirement : null).toBe(
      'Task requirement full text\nLine 2',
    )
    expect(taskSnapshot?.labelColorOverride).toBeNull()
    expect(taskSnapshot?.frame?.position).toEqual({ x: 100, y: 80 })
    expect(taskSnapshot?.frame?.size).toEqual({ width: 420, height: 260 })

    const terminalSnapshot = record.nodes.find(node => node.kind === 'terminal')
    expect(
      terminalSnapshot && terminalSnapshot.kind === 'terminal' ? terminalSnapshot.title : null,
    ).toBe('Terminal Title')
    expect(terminalSnapshot?.labelColorOverride).toBeNull()
    expect(terminalSnapshot?.frame?.position).toEqual({ x: 220, y: 40 })
    expect(terminalSnapshot?.frame?.size).toEqual({ width: 520, height: 320 })
    expect((terminalSnapshot as unknown as { scrollback?: unknown })?.scrollback).toBeUndefined()
  })

  it('clamps to 50 records when appending', () => {
    const base: SpaceArchiveRecord = {
      id: 'base',
      archivedAt: '2026-03-23T00:00:00.000Z',
      git: null,
      space: { id: 'space', name: 'Space', directoryPath: '/tmp', labelColor: null, rect: null },
      nodes: [],
    }

    const previous = Array.from({ length: 50 }, (_, index) => ({
      ...base,
      id: `record-${index}`,
    }))

    const next: SpaceArchiveRecord = {
      ...base,
      id: 'record-next',
    }

    const result = appendSpaceArchiveRecord(previous, next)
    expect(result).toHaveLength(50)
    expect(result[0].id).toBe('record-next')
    expect(result.some(item => item.id === 'record-49')).toBe(false)
  })

  it('captures archived descendant spaces and their nodes as one subtree snapshot', () => {
    const parent: WorkspaceSpaceState = {
      id: 'space-parent',
      name: 'Parent',
      directoryPath: '/repo',
      targetMountId: null,
      parentSpaceId: null,
      labelColor: 'blue',
      nodeIds: ['note-parent'],
      rect: null,
    }
    const child: WorkspaceSpaceState = {
      id: 'space-child',
      name: 'Child',
      directoryPath: '/repo/.opencove/worktrees/api',
      targetMountId: null,
      parentSpaceId: 'space-parent',
      labelColor: 'green',
      nodeIds: ['note-child'],
      rect: null,
    }

    const record = buildSpaceArchiveRecord({
      space: parent,
      spaces: [parent, child],
      nodes: [
        createNoteNode('note-parent', 'parent note'),
        createNoteNode('note-child', 'child note'),
      ],
      archivedAt: '2026-03-23T00:00:00.000Z',
      recordId: 'record-subtree',
    })

    expect(record.spaces?.map(space => space.id)).toEqual(['space-parent', 'space-child'])
    expect(record.nodes.map(node => node.id)).toEqual(['note-parent', 'note-child'])
    expect(record.spaces?.find(space => space.id === 'space-child')).toMatchObject({
      parentSpaceId: 'space-parent',
      directoryPath: '/repo/.opencove/worktrees/api',
      nodeIds: ['note-child'],
    })
  })

  it('derives a single archived Space from legacy records without spaces snapshots', () => {
    const record: SpaceArchiveRecord = {
      id: 'legacy',
      archivedAt: '2026-03-23T00:00:00.000Z',
      git: null,
      space: {
        id: 'space-legacy',
        name: 'Legacy',
        directoryPath: '/repo',
        labelColor: 'red',
        rect: null,
      },
      nodes: [
        {
          kind: 'note',
          id: 'note-legacy',
          title: 'Legacy note',
          frame: null,
          labelColorOverride: null,
          text: 'legacy',
        },
      ],
    }

    expect(getSpaceArchiveRecordSpaces(record)).toEqual([
      {
        id: 'space-legacy',
        name: 'Legacy',
        directoryPath: '/repo',
        targetMountId: null,
        parentSpaceId: null,
        boundary: null,
        labelColor: 'red',
        nodeIds: ['note-legacy'],
        rect: null,
      },
    ])
  })
})
