import type { Node } from '@xyflow/react'
import type { AgentRuntimeStatus } from '@contexts/agent/domain/types'
import type { AgentSettings, AgentProvider } from '@contexts/settings/domain/agentSettings'
import type { LabelColor, NodeLabelColorOverride } from '@shared/types/labelColor'
import type {
  CanvasImageMimeType,
  GitHubPullRequestSummary,
  TerminalPtyGeometry,
  TerminalRuntimeKind,
  WebsiteWindowSessionMode,
} from '@shared/contracts/dto'

export type { AgentRuntimeStatus } from '@contexts/agent/domain/types'

export type WorkspaceNodeKind =
  | 'terminal'
  | 'agent'
  | 'task'
  | 'note'
  | 'role'
  | 'image'
  | 'document'
  | 'website'

export type TaskRuntimeStatus = 'todo' | 'doing' | 'ai_done' | 'done'

export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent'

export type AgentLaunchMode = 'new' | 'resume'

export type ExecutionDirectoryMode = 'workspace' | 'custom'

export interface TaskAgentSessionRecord {
  id: string
  provider: AgentProvider
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  prompt: string
  model: string | null
  effectiveModel: string | null
  boundDirectory: string
  lastDirectory: string
  createdAt: string
  lastRunAt: string
  endedAt: string | null
  exitCode: number | null
  status: AgentRuntimeStatus
}

export interface AgentNodeData {
  provider: AgentProvider
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: AgentLaunchMode
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string
  expectedDirectory: string | null
  directoryMode: ExecutionDirectoryMode
  customDirectory: string | null
  shouldCreateDirectory: boolean
  taskId: string | null
}

export interface TaskNodeData {
  requirement: string
  status: TaskRuntimeStatus
  priority: TaskPriority
  tags: string[]
  linkedAgentNodeId: string | null
  agentSessions: TaskAgentSessionRecord[]
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  isEnriching?: boolean
  createdAt: string | null
  updatedAt: string | null
}

export interface NoteNodeData {
  text: string
}

export interface RoleRunRecord {
  id: string
  input: string
  prompt: string
  outputFormat: string
  provider: AgentProvider | null
  agentNodeId: string | null
  sessionId: string | null
  createdAt: string
}

export interface RoleNodeData {
  roleId: string
  roleName: string
  roleDescription: string
  promptTemplate: string
  inputHint: string
  outputFormat: string
  input: string
  selectedProvider: AgentProvider | null
  linkedAgentNodeId: string | null
  runHistory: RoleRunRecord[]
  createdAt: string | null
  updatedAt: string | null
}

export interface ImageNodeData {
  assetId: string
  mimeType: CanvasImageMimeType
  fileName: string | null
  naturalWidth: number | null
  naturalHeight: number | null
}

export interface DocumentNodeData {
  uri: string
}

export interface WebsiteNodeData {
  url: string
  pinned: boolean
  sessionMode: WebsiteWindowSessionMode
  profileId: string | null
}

export interface TerminalNodeData {
  [key: string]: unknown
  sessionId: string
  isLiveSessionReattach?: boolean
  profileId?: string | null
  runtimeKind?: TerminalRuntimeKind
  terminalGeometry?: TerminalPtyGeometry | null
  terminalProviderHint?: AgentProvider | null
  labelColorOverride?: NodeLabelColorOverride
  title: string
  titlePinnedByUser?: boolean
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
  note: NoteNodeData | null
  role?: RoleNodeData | null
  image: ImageNodeData | null
  document: DocumentNodeData | null
  website: WebsiteNodeData | null
}

export interface WorkspaceState {
  id: string
  name: string
  path: string
  worktreesRoot: string
  pullRequestBaseBranchOptions?: string[]
  environmentVariables?: Record<string, string>
  nodes: Node<TerminalNodeData>[]
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
  spaceArchiveRecords: SpaceArchiveRecord[]
}

export interface PersistedWorkspaceState {
  id: string
  name: string
  path: string
  worktreesRoot: string
  pullRequestBaseBranchOptions?: string[]
  environmentVariables?: Record<string, string>
  nodes: PersistedTerminalNode[]
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
  spaceArchiveRecords: SpaceArchiveRecord[]
}

export interface WorkspaceSpaceRect {
  x: number
  y: number
  width: number
  height: number
}

export interface WorkspaceSpaceState {
  id: string
  name: string
  directoryPath: string
  targetMountId: string | null
  labelColor: LabelColor | null
  nodeIds: string[]
  rect: WorkspaceSpaceRect | null
}

export interface SpaceArchiveRecord {
  id: string
  archivedAt: string
  git: SpaceArchiveGitSnapshot | null
  space: {
    id: string
    name: string
    directoryPath: string
    labelColor: LabelColor | null
    rect: WorkspaceSpaceRect | null
  }
  nodes: SpaceArchiveNodeSnapshot[]
}

export interface SpaceArchiveGitSnapshot {
  worktreePath: string | null
  branch: string | null
  head: string | null
  pullRequest: GitHubPullRequestSummary | null
}

export type SpaceArchiveNodeSnapshot =
  | SpaceArchiveTerminalSnapshot
  | SpaceArchiveAgentSnapshot
  | SpaceArchiveTaskSnapshot
  | SpaceArchiveNoteSnapshot

export interface SpaceArchiveTerminalSnapshot {
  kind: 'terminal'
  id: string
  title: string
  frame: NodeFrame | null
  labelColorOverride: NodeLabelColorOverride
  runtimeKind: TerminalRuntimeKind | null
  executionDirectory: string | null
  expectedDirectory: string | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
}

export interface SpaceArchiveAgentSnapshot {
  kind: 'agent'
  id: string
  title: string
  frame: NodeFrame | null
  labelColorOverride: NodeLabelColorOverride
  status: AgentRuntimeStatus | null
  provider: AgentProvider | null
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: AgentLaunchMode | null
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string | null
  expectedDirectory: string | null
  directoryMode: ExecutionDirectoryMode | null
  customDirectory: string | null
  shouldCreateDirectory: boolean
  taskId: string | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
}

export interface SpaceArchiveTaskSnapshot {
  kind: 'task'
  id: string
  title: string
  frame: NodeFrame | null
  labelColorOverride: NodeLabelColorOverride
  requirement: string
  status: TaskRuntimeStatus
  priority: TaskPriority
  tags: string[]
  linkedAgentNodeId: string | null
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  createdAt: string | null
  updatedAt: string | null
}

export interface SpaceArchiveNoteSnapshot {
  kind: 'note'
  id: string
  title: string
  frame: NodeFrame | null
  labelColorOverride: NodeLabelColorOverride
  text: string
}

export interface PersistedTerminalNode {
  id: string
  sessionId?: string | null
  title: string
  titlePinnedByUser?: boolean
  position: Point
  width: number
  height: number
  kind: WorkspaceNodeKind
  profileId?: string | null
  runtimeKind?: TerminalRuntimeKind
  terminalGeometry?: TerminalPtyGeometry | null
  terminalProviderHint?: AgentProvider | null
  labelColorOverride?: NodeLabelColorOverride
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent: AgentNodeData | null
  task:
    | TaskNodeData
    | NoteNodeData
    | RoleNodeData
    | ImageNodeData
    | DocumentNodeData
    | WebsiteNodeData
    | null
}

export interface PersistedAppState {
  formatVersion: number
  activeWorkspaceId: string | null
  workspaces: PersistedWorkspaceState[]
  settings: AgentSettings
}

export interface WorkspaceViewport {
  x: number
  y: number
  zoom: number
}

export const DEFAULT_WORKSPACE_VIEWPORT: WorkspaceViewport = {
  x: 0,
  y: 0,
  zoom: 1,
}

export const DEFAULT_WORKSPACE_MINIMAP_VISIBLE = true

export interface Size {
  width: number
  height: number
}

export interface Point {
  x: number
  y: number
}

export interface NodeFrame {
  position: Point
  size: Size
}
