import type { Node } from '@xyflow/react'
import type {
  AgentNodeData,
  Point,
  Size,
  SpaceArchiveRecord,
  TaskPriority,
  TaskRuntimeStatus,
  TerminalNodeData,
  WorkspaceNodeKind,
  WorkspaceSpaceRect,
  WorkspaceSpaceState,
  WorkspaceViewport,
} from '../../types'
import type { AgentSettings } from '@contexts/settings/domain/agentSettings'
import type { MountDto, TerminalPtyGeometry, TerminalRuntimeKind } from '@shared/contracts/dto'
import type { LabelColor } from '@shared/types/labelColor'

export type WorkspaceCanvasMessageTone = 'info' | 'warning' | 'error'

export type ShowWorkspaceCanvasMessage = (
  message: string,
  tone?: WorkspaceCanvasMessageTone,
) => void

export interface WorkspaceCanvasProps {
  workspaceId: string
  onShowMessage?: ShowWorkspaceCanvasMessage
  workspacePath: string
  environmentVariables?: Record<string, string>
  worktreesRoot: string
  nodes: Node<TerminalNodeData>[]
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onRequestPersistFlush?: () => void
  spaces: WorkspaceSpaceState[]
  activeSpaceId: string | null
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onActiveSpaceChange: (spaceId: string | null) => void
  shortcutsEnabled?: boolean
  onAppendSpaceArchiveRecord: (record: SpaceArchiveRecord) => void
  viewport: WorkspaceViewport
  isMinimapVisible: boolean
  onViewportChange: (viewport: WorkspaceViewport) => void
  onMinimapVisibilityChange: (isVisible: boolean) => void
  agentSettings: AgentSettings
  isFocusNodeTargetZoomPreviewing?: boolean
  focusNodeId?: string | null
  focusSpaceId?: string | null
  focusSequence?: number
}

export interface PaneContextMenuState {
  kind: 'pane'
  x: number
  y: number
  flowX: number
  flowY: number
}

export interface SelectionContextMenuState {
  kind: 'selection'
  x: number
  y: number
}

export type ContextMenuState = PaneContextMenuState | SelectionContextMenuState

export interface SpaceActionMenuState {
  spaceId: string
  x: number
  y: number
}

export interface SpaceWorktreeDialogState {
  spaceId: string
  initialViewMode: 'create' | 'archive'
}

export interface SelectionDraftState {
  startX: number
  startY: number
  currentX: number
  currentY: number
  pointerId: number
  toggleSelection: boolean
  selectedNodeIdsAtStart: string[]
  selectedSpaceIdsAtStart: string[]
  startSpaceId: string | null
  phase: 'active' | 'settling'
}

export interface EmptySelectionPromptState {
  x: number
  y: number
  rect: WorkspaceSpaceRect
}

export interface SpaceTargetMountPickerState {
  nodeIds: string[]
  rect: WorkspaceSpaceRect | null
  mounts: MountDto[]
  selectedMountId: string
}

export interface SpaceVisual {
  id: string
  name: string
  directoryPath: string
  targetMountId: string | null
  labelColor: LabelColor | null
  rect: WorkspaceSpaceRect
  hasExplicitRect: boolean
}

export interface SpaceDragState {
  pointerId: number
  spaceId: string
  startFlow: Point
  startClient: Point
  shiftKey: boolean
  initialRect: WorkspaceSpaceRect
  allNodePositions: Map<string, Point>
  initialNodePositions: Map<string, Point>
  ownedBounds: { left: number; top: number; right: number; bottom: number } | null
  handle:
    | { kind: 'move' }
    | {
        kind: 'resize'
        edges: Partial<Record<'top' | 'right' | 'bottom' | 'left', true>>
      }
}

export type TrackpadGestureAction = 'pan' | 'pinch'
export type TrackpadGestureTarget = 'canvas' | 'node'
export type CanvasWheelGesturePhase = 'active' | 'settling'

export interface CanvasWheelGestureSessionState {
  action: TrackpadGestureAction
  owner: TrackpadGestureTarget
  phase: CanvasWheelGesturePhase
  lastTimestamp: number
}

export type TrackpadGestureLockState = CanvasWheelGestureSessionState

export interface TaskCreatorState {
  anchor: Point
  title: string
  requirement: string
  priority: TaskPriority
  selectedTags: string[]
  autoGenerateTitle: boolean
  isGeneratingTitle: boolean
  isCreating: boolean
  error: string | null
}

export interface RoleCreatorState {
  anchor: Point
  mode: 'create' | 'edit'
  roleId: string | null
  name: string
  description: string
  promptTemplate: string
  inputHint: string
  outputFormat: string
  isCreating: boolean
  error: string | null
}

export interface TaskEditorState {
  nodeId: string
  initialTitle: string
  initialAutoGeneratedTitle: boolean
  titleGeneratedInEditor: boolean
  title: string
  requirement: string
  priority: TaskPriority
  selectedTags: string[]
  autoGenerateTitle: boolean
  isGeneratingTitle: boolean
  isSaving: boolean
  error: string | null
}

export interface NodeDeleteConfirmationState {
  nodeIds: string[]
  primaryNodeKind: WorkspaceNodeKind
  primaryNodeTitle: string
  emptyingSpaces: Array<{
    id: string
    name: string
  }>
}

export interface SpaceWorktreeMismatchDropWarningState {
  spaceId: string
  spaceName: string
  agentCount: number
  terminalCount: number
}

export interface CreateNodeInput {
  sessionId: string
  profileId?: string | null
  runtimeKind?: TerminalRuntimeKind
  terminalGeometry?: TerminalPtyGeometry | null
  title: string
  anchor: Point
  kind: 'terminal' | 'agent'
  agent?: AgentNodeData | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  placement?: NodePlacementOptions
}

export type NodePlacementDirection = 'right' | 'down' | 'left' | 'up'

export interface NodePlacementOptions {
  targetSpaceRect?: WorkspaceSpaceRect | null
  preferredDirection?: NodePlacementDirection
  // Flow-space rectangles that new nodes should avoid overlapping (e.g. in-space overlays).
  avoidRects?: WorkspaceSpaceRect[]
}

export interface NodeCreationPlacementOptions extends NodePlacementOptions {
  focusViewportOnCreate?: boolean
  sizeOverride?: Size
}

export interface WorkspaceCanvasQuickPreviewState {
  spaceId: string
  mountId: string | null
  uri: string
  title: string
  kind: 'document' | 'image' | 'audio' | 'video'
  rect: WorkspaceSpaceRect
  createAnchor: Point
  createPlacement?: NodeCreationPlacementOptions
  naturalWidth?: number | null
  naturalHeight?: number | null
}

export type QuickUpdateTaskTitle = (nodeId: string, title: string) => void
export type QuickUpdateTaskRequirement = (nodeId: string, requirement: string) => void
export type UpdateTaskStatus = (nodeId: string, status: TaskRuntimeStatus) => void
export type UpdateNodeScrollback = (nodeId: string, scrollback: string) => void
